<a href="https://colab.research.google.com/github/SudhaSagasranaman/Cancer_prediction_Using-Logistics-Regression-model-program/blob/main/RealisticClassification2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv('realistic_classification2.csv')
df.head()

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0   0.882861   2.556225  -1.459634  -1.063957  -0.199371  -0.897641   
1   0.788093   0.114714   2.401184  -0.953390   0.617504   1.446727   
2  -0.600871   1.712959  -1.203358   0.820962  -2.042741   0.412667   
3   2.267351   0.182555  -0.850543  -0.703506   0.664847   2.004257   
4  -0.613007   3.369510  -0.782090  -1.379381  -2.691947   0.433527   

   Feature_7  Feature_8  Target  
0   2.052610  -3.235077       1  
1  -0.809697   0.262187       0  
2  -1.867888   0.175067       0  
3   1.786042   2.781552       2  
4  -2.546267  -1.638139       0

In [6]:
df.isnull().sum()

Feature_1    0
Feature_2    0
Feature_3    0
Feature_4    0
Feature_5    0
Feature_6    0
Feature_7    0
Feature_8    0
Target       0
dtype: int64

In [7]:
df.shape

(1200, 9)

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,LeakyReLU,ReLU,PReLU
from tensorflow.keras.callbacks import EarlyStopping
model = Sequential()
model.add(Dense(units = 8,activation = 'relu'))
model.add(Dense(units = 6,activation = 'relu'))
model.add(Dense(units = 6,activation = 'relu'))
model.add(Dense(units = 1,activation = 'sigmoid'))

opt = tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])


early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=20,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
)
model.fit(xtrain,ytrain, validation_split=0.33,batch_size = 10, epochs = 1000,callbacks=[early_stopping])


Epoch 1/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - accuracy: 0.3670 - loss: 0.2540 - val_accuracy: 0.3470 - val_loss: -3.1084
Epoch 2/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3797 - loss: -11.3035 - val_accuracy: 0.3912 - val_loss: -133.5806
Epoch 3/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3826 - loss: -275.2899 - val_accuracy: 0.3628 - val_loss: -1376.8590
Epoch 4/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3750 - loss: -1751.7148 - val_accuracy: 0.3659 - val_loss: -5643.9575
Epoch 5/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3945 - loss: -6621.3931 - val_accuracy: 0.3344 - val_loss: -16587.7930
Epoch 6/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3840 - loss: -14944.7422 - val_accuracy: 0.3375 - val_loss: -39868.3477
Epoch 7/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3855 - loss: -40661.1836 - val_accuracy: 0.3407 - val_loss: -84321.0625
Epoch 8/1000
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step -

In [8]:
x = df.drop(['Target'],axis = 1)

y = df['Target']

In [9]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2,random_state = 42)


In [11]:
print(ytest)

ytest = ytest.astype(int)


y_pred = model.predict(xtest)
y_pred = (y_pred > 0.5).astype(int)

# Assuming ytest is your true labels
cm = confusion_matrix(ytest, y_pred)
print(cm)
accuracy = accuracy_score(ytest,y_pred)
print(accuracy)


1178    2
865     2
101     1
439     1
58      1
       ..
382     2
867     0
542     0
1193    1
874     1
Name: Target, Length: 240, dtype: int64
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step
[[ 0 87  0]
 [ 0 67  0]
 [ 0 86  0]]
0.2791666666666667
